{% set version = "1.0-10.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-norm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/norm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/norm/norm_{{ version }}.tar.gz
  sha256: 4384791af74c1008238f036abe0dda4b4048b9700cc4acd7b45025598fd20cc7

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('norm')"           # [not win]
    - "\"%R%\" -e \"library('norm')\""  # [win]

about:
  home: http://www.stat.psu.edu/~jls/misoftwa.html#aut
  license: Other
  license_file: LICENSE
  summary: Analysis of multivariate normal datasets with missing values
  license_family: OTHER

extra:
  recipe-maintainers:
    - conda-forge/r
