appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: HQymHoALk76P+PLrFm7mK00L7UtXozcsNv7TF/ysap2ZZnS9R3hHPqtb72rL+ySIWTUaVz5hI0sveB9ih3RK9hSjHCrvwzX1T9aZzUDabzhbpukPqtr9aJGistK6H11NEc2SeNb2egay7HCCXJAvvTa6QNRdsORUegHLWrI7dGmmXQvNQaRZfuCsbgtSdjaB6MBEQcuDY3ax01CRXByGXMLOA1LTgN6N/6CaKYTxafNuQ3Jx6CrJoeWA8v6Jj4sZwkz7S0iM5yNXupRVC9FUOEOPa8jSMnlQ3tYIyhi38a+5u3sTp4AwGxXDjIIwpptzacU2i6WD+2wfiJ2Lxp/wLmPVF6M+SJp+15uOFiHgFHbriFtJNUHmfx9ACnWTwtITry5K/1Kn40ywFwT6GCt5idmqyjpj2JPjBsQZdD9qEQyf01joQy9I3DF8HO6rsf3giIyWp3xG6sgLesIgwaT2foahzqB5EmHkQw6iWoMDbFo/u94bNk3yh+47iYykqNLZtQNHbm17/a2qyb2F4mQSvHOC2qAV1P6rH7+1qPggCYA1S0VUE3xFjrZ28ZS6lJwvJpRWlBo1SXirTFn2rIMDBlhx4nZM9T9wFiyZvR6gZEhw0++tN3waNMAk7fFmBvu/zW/sVfuJO2UF/sq3AIyS/P5C4n1xv9PWGPGqi9sqHXA=}
